import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/lib/ThemeRegistry";
import Navbar from "@/layout/Navbar";
import QueryProvider from "@/lib/QueryProvider";
import { getCurrentUser } from "@/lib/getCurrentUser";
import ToastProvider from "@/lib/ToasterProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const currentUser = await getCurrentUser();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <ThemeRegistry>
            <Navbar user={currentUser} />
            {children}
            <ToastProvider />
          </ThemeRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
